### ISSUE TITLE
Publishing/Migrating Database Issue

### ISSUE THREAD

**Issue by ghost** [Lecturize/Laravel-Followers#1]
When publishing your file...
"php artisan vendor:publish --provider="vendocrat\Followers\FollowersServiceProvider"

You need to change your FollowersServiceProvider file location to "database/migrations/create_followers_table.stub.php"

Currently it's "database/migrations/create_media_table.php.stub" and your table name is "create_followers_table.stub"

**Comment by AlexanderPoellmann** [comment]
Sorry for the very late reply. I've fixed that!
