### ISSUE TITLE
Eager-loading?

### ISSUE THREAD

**Issue by ghost** [Lecturize/Laravel-Followers#3]
Very cool package, even if it is a work in progress - thanks for sharing it!

One issue i'm running into is eager-loading. On search results for users, i need to do:

```php
User::with('followers')->get();
```
And at the moment, the package seems to only allow using $user->getFollowers().

Is it possible to eager load the relations from the traits?

**Comment by AlexanderPoellmann** [comment]
`getFollowers()` is merely a convenience method. You can eager-load like so:

`User::with('follower')->get();`
